### ISSUE TITLE
Trouble updating files

### ISSUE THREAD

**Issue by MarshallVisions** [fbiego/IOS-ESP32#3]
Hi. I am really excited about this because I was able to upload a Squareline Studio project to my WT32-SC01 on PlatformIO, so thank you so much! I have been able to replace the ui, ui_events, ui_helpers, and the imgs,fonts files using a modified version of the Squareline project that you included, but when it boots up, only the top quarter is rendered. Having trouble even reproducing that now... Folder structure seems different.. u.h not defined... tons of errors.. #include "ui.h" gives error, " lv_obj_t " undefinied.. screens in your platformIO project are inside the u.h files but Squareline exports them to their own files which causes redeclaration errors... What are the steps needed to go from your Squareline project to a working PlatformIO build? Thanks..

**Comment by fbiego** [comment]
I would recommend you check the following template
https://github.com/fbiego/wt32-lvgl-template
I have tested with SquareLine v1.2.3

**Comment by MarshallVisions** [comment]
Hi again! That worked to upload my own project! But I am still facing the issue where only part of the screen is rendered (top 1/4 in portrait mode and (1/8th of the screen coming from the right when in landscape mode)

**Comment by MarshallVisions** [comment]
Got it working by starting a Squareline project from scratch!
